### ISSUE TITLE
被艾特没进入过for循环导致下面无法获取发送信息

### ISSUE THREAD

**Issue by w9931125** [rxf113/mirai-qq-bot#4]
经过测试没有进入过
![image](https://user-images.githubusercontent.com/52391192/218694351-a4fba200-36d1-4477-a669-633489a941e7.png)
这几行代码，艾特的情况，是bug吗

**Comment by rxf113** [comment]
这里没有错，可以bebug看看具体情况

**Comment by w9931125** [comment]
> 这里没有错，可以bebug看看具体情况

如果timeout和HTTP 429是网络的问题吗

**Comment by rxf113** [comment]
是不是你需要的结果很长，可以调大getAnswerByChatGPT方法里的，请求的 timeout

**Comment by w9931125** [comment]
> 是的，不知道为啥有时候openAi返回回来的时候的答案总是被截取了一下，想说的话没有表达完

**Comment by rxf113** [comment]
把getAnswerByChatGPT方法里的 maxTokens 调大
